const {
  DIGIT_ZERO_GLYPH,
  DIGIT_ONE_GLYPH,
  DIGIT_TWO_GLYPH,
  DIGIT_THREE_GLYPH,
  DIGIT_FOUR_GLYPH,
  DIGIT_FIVE_GLYPH,
  DIGIT_SIX_GLYPH,
  DIGIT_SEVEN_GLYPH,
  DIGIT_EIGHT_GLYPH,
  DIGIT_NINE_GLYPH
} = require('./glyps')

const GLYPH_SIZE = 3
const GLYPHS_PER_ENTRY = 9
const GLYPH_TO_DIGIT_MAP = {
  [DIGIT_ZERO_GLYPH]: 0,
  [DIGIT_ONE_GLYPH]: 1,
  [DIGIT_TWO_GLYPH]: 2,
  [DIGIT_THREE_GLYPH]: 3,
  [DIGIT_FOUR_GLYPH]: 4,
  [DIGIT_FIVE_GLYPH]: 5,
  [DIGIT_SIX_GLYPH]: 6,
  [DIGIT_SEVEN_GLYPH]: 7,
  [DIGIT_EIGHT_GLYPH]: 8,
  [DIGIT_NINE_GLYPH]: 9
}

const DOCUMENT_ENTRY_SEPARATOR = '\n                           \n'

const ILLEGIBLE_NUMBER_STATUS = Symbol('ILLEGIBLE_NUMBER_STATUS')
const INVALID_NUMBER_STATUS = Symbol('INVALID_NUMBER_STATUS')
const VALID_NUMBER_STATUS = Symbol('VALID_NUMBER_STATUS')

module.exports = {
  GLYPH_SIZE,
  GLYPHS_PER_ENTRY,
  GLYPH_TO_DIGIT_MAP,
  DOCUMENT_ENTRY_SEPARATOR,
  ILLEGIBLE_NUMBER_STATUS,
  INVALID_NUMBER_STATUS,
  VALID_NUMBER_STATUS
}
