const DOCUMENT_ENTRY_SEPARATOR = '\n                           \n'

const ILLEGIBLE_NUMBER_STATUS = Symbol('ILLEGIBLE_NUMBER_STATUS')
const INVALID_NUMBER_STATUS = Symbol('INVALID_NUMBER_STATUS')
const VALID_NUMBER_STATUS = Symbol('VALID_NUMBER_STATUS')

module.exports = {
  DOCUMENT_ENTRY_SEPARATOR,
  ILLEGIBLE_NUMBER_STATUS,
  INVALID_NUMBER_STATUS,
  VALID_NUMBER_STATUS
}
